#!/bin/bash

HARTS=4
MEMORY=250.1M
STORAGE="-drive file=main.storage,if=none,id=main"
DEVICES="-device nvme,serial=deadbeef,drive=main -device bochs-display,bus=pcie.0"

KERNEL=kernel

(cd bin && qemu-system-riscv64 -nographic -machine virt -cpu rv64 -d guest_errors,unimp -D qemu.log -smp $HARTS -m $MEMORY -bios default -kernel $KERNEL -serial mon:stdio -drive if=none,format=raw,file=main.storage,id=main $DEVICES)
