#!/bin/bash

(cd bin && qemu-system-riscv64 -machine virt -cpu rv64 -d guest_errors,unimp -D qemu.log -smp 1 -m 128M -bios none -nographic -kernel kernel -drive if=none,format=raw,file=main.storage,id=main -device virtio-blk-device,scsi=off,drive=main -device virtio-gpu-device -device virtio-keyboard-device -device virtio-mouse-device)
